### ISSUE TITLE
Bins should be left installed to bin, not to "Server"

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-win-installer#12]
Fine to let them overlap, that's what they do on Linux - it works by design. A bit surprised it works fine the way it is right now, actually - I guess that means my fix to not require the containing directory to be named bin worked :D but it makes it harder to use - for instance, CMake won't be able to find `osvr_json_to_c`

**Comment by gfrolov** [comment]
Moved binaries from "Server" to "bin" - https://github.com/OSVR/OSVR-win-installer/commit/118611a134a4dc6b5ff09d7b03fbb333756ffdd5
