### ISSUE TITLE
Redistributing licenses and notices

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-win-installer#13]
Must redistribute all NOTICE files from Apache 2 licensed projects (can concatencate them)

Must redistribute the license text and details on sources from OpenSceneGraph as used in trackerviewer.

**Comment by gfrolov** [comment]
Fixed via https://github.com/OSVR/OSVR-win-installer/commit/aa7cd9177271c465dc86c82af96c8dd721ae462f
