### ISSUE TITLE
64 and 32-bit SDK installers, multiple variants installed at once.

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-win-installer#14]
Can't install both at once - having any one of the four installer variants will block the others saying that a later version is installed.  Don't know if we should have separate (is it package?) GUIDs for each of those variants, but at least some people, if not most, who want one of the SDKs will want both - I'd almost do what MS does and make a single SDK installer that includes both the 32-bit and 64-bit variants, though that would likely be more work.

**Comment by gfrolov** [comment]
I'm going to look into bundling 32 and 64 bit together or using separate GUIDs. @rpavlik , if we bundle both 32 and 64 variants, then which bitness are we using for binaries (server, central, etc.) ?

**Comment by gfrolov** [comment]
Fixed via #25
