### ISSUE TITLE
Update CI

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-win-installer#16]
Should trigger not just on github update, but also when post-deploy tasks complete. Might need to add another general step after "deploy" to shepherd all the things that rebuild after a core build, so you can "join" them.

(And, then, update the getting started doc with the link to the installer and remove the note about the old installer being outdated.)

**Comment by gfrolov** [comment]
@rpavlik ,
I added a trigger a build whenever core deploy similar to Tracker Viewer. Are you referring to core deploy job as "post deploy tasks" or something else?
Also configured it to build weekly.
There was a pull request last week - https://github.com/OSVR/OSVR-Docs/pull/30 that added info on installer and I made additional edits to those right now - https://github.com/OSVR/OSVR-Docs/commit/2a287d544b0042afcef9bcbbd69f32f6e4e13f92

**Comment by rpavlik** [comment]
You might want it to trigger after tracker viewer or whatever the
last-building thing you incorporate is, otherwise you'll get mixed or
outdated binaries - that's what I meant by post deploy tasks (all the
things that build after we deploy Windows core binaries)

**Comment by gfrolov** [comment]
I added the following build triggers : OSVR-Core deploy, RM artifacts, OSVR-Central, and OSVR-Config. 
We have only tracker viewer project that depends on Core deploy, but it hasn't changed in a while, so we should be safe on that side.
