### ISSUE TITLE
Bundle the *-ver.txt files

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-win-installer#18]
Please include the various `*-ver.txt` files generated on the CI with the git-describe information (and consider making one for this repo too), so that users have some way of determining what version of things they actually have installed on their system.

**Comment by gfrolov** [comment]
@rpavlik, so there are osvr-ver.txt files from OSVR-Core, Tracker Viewer and RM. Because we include all 3 in Runtime and SDK, should we be including all three of them?

**Comment by rpavlik** [comment]
Well, include the one from the place you're keeping the OSVR Core runtime
files from. In theory they should be the same (except maybe for rm), but it
identifies the version of the core files (client kit, etc) so let that be
your guide.

On Thu, Jul 14, 2016, 4:43 PM Georgiy Frolov notifications@github.com
wrote:

> @rpavlik https://github.com/rpavlik, so there are osvr-ver.txt files
> from OSVR-Core, Tracker Viewer and RM. Because we include all 3 in Runtime
> and SDK, should we be including all three of them?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/OSVR/OSVR-win-installer/issues/18#issuecomment-232801475,
> or mute the thread
> https://github.com/notifications/unsubscribe/AADuyUhfk6L0G7cvsOC1EaqCipaFvweAks5qVq2GgaJpZM4JDgFB
> .
> 
> ## 
> 
> Ryan A. Pavlik, Ph.D.
> CTO - OSVR Platform
> Sensics, Inc.
> www.sensics.com

## 

Latest news and blog posts (subscribe here 
http://sensics.com/subscribe-to-our-mailing-list/ to get weekly updates):

July 20: Conversation with Dio Gonzalez, Principal Software Engineer at 
Unity Labs 
http://sensics.com/vrguy-podcast-episode-19-dio-gonzalez-principal-software-developer-unity-labs/

July 19: Sensics and LaputaVR team up to provide OSVR support to LaputaVR 
devices 
http://sensics.com/sensics-laputa-vr-team-provide-osvr-support-laputa-vr-devices/

July 13: VRguy podcast: Shaun Williams, CEO of MAG games 
http://bit.ly/29vCqIW

**Comment by gfrolov** [comment]
Fixed via #25
