### ISSUE TITLE
Installer versioning

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-win-installer#3]
Right now, a version is manually coded in `Setup.nsi` and doesn't match the build version. It does look like the `osvr-ver.txt` file is getting packaged, which contains the official `git describe`-derived, precise version. Would be preferable to generate the packaging version from this. Use of this version string:
- The first three components (specifically, all the numeric tokens separated by `.` or `-`) can (and have been, on access.osvr.com) be used as a dotted-decimal version: specifically, the dotted portion is the most recent tagged version, while the number after the dash is the number of commits since the tag.
- The last component (the one starting with `g`) identifies the specific git commit in OSVR-Core corresponding to the version (because due to branches, a tag and number of commits do not uniquely identify a revision, but commit ids are sha hashes and thus not very useful as numeric versions)
- The full string, perhaps without leading v, should be used when we can use a string for the version.

**Comment by leemichaelRazer** [comment]
installer now uses osvr-ver.txt file located in the distribution directory.
