### ISSUE TITLE
Instructions and Docs

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-win-installer#5]
Build instructions should be converted from a blob (docx) to Markdown, preferably in README. Also, only a single version needs to be kept in version control, since it allows us to access older versions if desired.

**Comment by rpavlik** [comment]
The additional documentation/capabilities in those docs can either go in `README.md` or a separate `.md` file, if they make the `README.md` too long. (That's usually the deciding factor I use as for whether to make a separate file for documentation: the length of README. If we can keep it all in one file, so much the better.)

**Comment by leemichaelRazer** [comment]
MS Word doc has been converted.
